services:
  license-admin:
    build:
      context: .
      dockerfile: docker/Dockerfile.admin
    container_name: license-admin
    env_file:
      - .env
    ports:
      - "3080:3080"
    volumes:
      - ./data:/srv/data
    restart: unless-stopped

  license-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: license-api
    env_file:
      - .env
    ports:
      - "3445:3445"
    volumes:
      - ./data:/srv/data
    restart: unless-stopped
