services:
  licensing:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: LicensingService
    env_file:
      - .env
    ports:
      - "${PORT:-3080}:3080"
    volumes:
      - ./data:/app/data
      - ./keys:/app/keys
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3080/health"]
      interval: 10s
      timeout: 3s
      retries: 5
