# Compose v2+ automatically uses the latest schema; 'version:' is obsolete
# See: https://docs.docker.com/compose/  and community note about deprecation warnings
# Service: one container serving Admin UI and Public API
services:
  licensing:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: licensing-server
    env_file:
      - .env
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ./data:/app/data
      - ./keys:/app/keys
      - ./logs:/app/logs
    restart: unless-stopped
