services:
  licensing:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: licensing-server
    env_file:
      - .env
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ./data:/app/data
      - ./keys:/app/keys
      - ./logs:/app/logs
    restart: unless-stopped
